# Generated by Django 3.2.1 on 2021-06-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='img',
            field=models.ImageField(default='', upload_to='software_img/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
