# Generated by Django 3.2.1 on 2021-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20210628_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
