# Generated by Django 3.2.1 on 2021-07-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_software_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='software',
            name='dsc',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
