# Generated by Django 3.2.1 on 2021-07-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_auto_20210706_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
