# Generated by Django 3.2.1 on 2021-07-16 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_auto_20210709_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.CharField(default='', max_length=20)),
                ('value', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
